const names = require('./04-names')
const greeting = require('./05-utils')
const data = require('./06-alternative-flavor')
require('./07-mind-grenade')
greeting('jeff')
greeting(names.olga)
greeting(names.peter)
greeting(data.singlePerson.name)
